version: "3.8"
services:
  backend-auth:
    image: ${IMAGE}
    env_file:
      - .env
    # ports:
    #   - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - wealth
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
        compress: "true"
    healthcheck:
      test: curl --fail http://localhost:${WEB_PORT}/metrics || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 10s
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${NETWORK_ENV}-wealth
        - traefik.http.services.backend-auth.loadbalancer.server.port=${WEB_PORT}
        - traefik.http.routers.backend-auth.rule=Host(`${TRAEFIK_DOMAIN}`)
        - traefik.http.routers.backend-auth.entrypoints=websecure
        - traefik.http.routers.backend-auth.tls=true
      replicas: ${INSTANCE_NUM}
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        max_failure_ratio: 0
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
networks:
  wealth:
      name: ${NETWORK_ENV}-wealth